[project]
name            = "pyright-venv-config"
version         = "0.1.0"
description     = "Add your description here"
requires-python = ">=3.13"
dependencies    = []


[tool.pyright]
venvPath = "."
venv     = ".venv"
python   = "3.13"
